
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:

 # FIXME: No unit tests :-(
  # Tests:
  #   runs-on: ubuntu-latest
  #   container: registry.opensuse.org/yast/head/containers/yast-ruby:latest

  #   steps:

  #   - name: Git Checkout
  #     uses: actions/checkout@v2

  #   # just for easier debugging...
  #   - name: Inspect Installed Packages
  #     run: rpm -qa | sort

  #   - name: Unit Tests
  #     run: rake test:unit
  #     # enable code coverage reporting
  #     env:
  #       COVERAGE: 1

  #   # send the coverage report to coveralls.io
  #   - name: Coveralls Report
  #     uses: coverallsapp/github-action@master
  #     with:
  #       github-token: ${{ secrets.GITHUB_TOKEN }}

  Rubocop:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distro:  [ "tumbleweed", "leap_latest" ]

    container:
      image: registry.opensuse.org/yast/head/containers_${{matrix.distro}}/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Rubocop
      run: rake check:rubocop

  Package:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distro:  [ "tumbleweed", "leap_latest" ]

    container:
      image: registry.opensuse.org/yast/head/containers_${{matrix.distro}}/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Package Build
      run: yast-ci-ruby -o package

  Yardoc:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distro: [ "leap_latest" ]

    container:
      image: registry.opensuse.org/yast/head/containers_${{matrix.distro}}/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Yardoc
      run: rake check:doc

  # downloading the Docker image takes some time so bundling several fast
  # checks into one job avoids that overhead
  Checks:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distro: [ "leap_latest" ]

    container:
      image: registry.opensuse.org/yast/head/containers_${{matrix.distro}}/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: POT Check
      run: rake check:pot
